events { 
    worker_connections 1024; 
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Définition des blocs amont (Upstreams) vers les microservices via le back-network
    upstream auth_service { server service-auth:8082; }
    upstream calcul_service { server service-calcul:8083; }
    upstream lecture_service { server service-lecture:8084; }
    upstream alerte_service { server gestion-alerte:8085; }

    server {
        listen 8000;
        server_name localhost;

        # --------------------------------------------------------
        # CONFIGURATION DES EN-TÊTES CORS GLOBAL (Pour le navigateur)
        # --------------------------------------------------------
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,X-Requested-With' always;

        # Interception des requêtes de pré-vérification OPTIONS (CORS Preflight)
        if ($request_method = 'OPTIONS') {
            return 204;
        }

        # --------------------------------------------------------
        # ROUTAGE DES MICROSERVICES METIERS
        # --------------------------------------------------------

        # 1. Service Authentification (JWT)
        location /api/auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Service Calcul Énergétique & Carbone
        location /api/calcul/ {
            proxy_pass http://calcul_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Service Lecture de Données (Historique / Données épurées)
        location /api/donnees/ {
            proxy_pass http://lecture_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. Service Gestion d'Alertes 
        location /api/alertes/ {
            proxy_pass http://alerte_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}