
services:

  # ==========================================
  # 1. COUCHE FRONTEND & API GATEWAY
  # ==========================================
  frontend:
    build: ./frontend
    container_name: greenops_frontend
    ports:
      - "80:80"
    networks:
      - front-network # Zone publique uniquement

  api-gateway:
    image: nginx:stable-alpine
    container_name: greenops_api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-auth
      - service-calcul
      - service-lecture
      - gestion-alerte
    networks:
      - front-network # Reçoit les requêtes du front
      - back-network  # Les distribue aux microservices

  # ==========================================
  # 2. COUCHE SERVICES MÉTIERS
  # ==========================================
  service-auth:
    build: ./service-auth
    container_name: greenops_service_auth
    expose:
      - "8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-network # Jointure passerelle & base de données

  service-calcul:
    build: ./service-calcul
    container_name: greenops_service_calcul
    expose:
      - "8083"
    depends_on:
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - back-network # Reçoit les ordres de la Gateway
      - data-network # Communique avec Postgres, Redis et Prometheus

  service-lecture:
    build: ./service-lecture
    container_name: greenops_service_lecture
    expose:
      - "8084"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-network
      - data-network

  gestion-alerte:
    build: ./gestion-alerte
    container_name: greenops_gestion_alerte
    expose:
      - "8085"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - back-network
      - data-network

  # ==========================================
  # 3. COUCHE STOCKAGE & CACHE
  # ==========================================
  postgres:
    image: postgres:15-alpine
    container_name: greenops_postgres
    environment:
      POSTGRES_USER: greenops_user
      POSTGRES_PASSWORD: greenops_password
      POSTGRES_DB: greenops_db
    ports:
      - "5432:5432" # Optionnel : à retirer en prod pour renforcer l'isolation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greenops_user -d greenops_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - back-network # Pour l'accès initial du service Auth
      - data-network # Pour l'accès des services de calcul, lecture et alerte

  redis:
    image: redis:7-alpine
    container_name: greenops_redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - data-network # Seuls les microservices du data-network peuvent le manipuler

  # ==========================================
  # 4. COUCHE SERVICES TECHNIQUES (MONITORING)
  # ==========================================
  scaphandre:
    image: hubblo/scaphandre:latest
    container_name: greenops_scaphandre
    volumes:
      - /proc:/user/metrics/proc:ro
    ports:
      - "8080:8080"
    command: 
      - prometheus
      - --vm
    networks:
      data-network: # Isolé dans le réseau technique
        aliases:
          - scaphandre
  
  service-simulator:
    build: ./service-simulator # Chemin vers le dossier contenant le Dockerfile et main.py
    container_name: greenops_simulator
    ports:
      - "8089:8000" # Expose le port 8000 interne sur le port 8089 de Windows (pour tester)
    networks:
      - data-network

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: greenops_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    depends_on:
      - scaphandre
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/ready"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - data-network # Scrape Scaphandre et répond au Service Calcul

  grafana:
    image: grafana/grafana:10.4.1
    container_name: greenops_grafana
    ports:
      - "3000:3000" # Reste accessible pour l'admin de l'infrastructure
    environment:
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - back-network # Pour l'accès de la Gateway (si besoin d'une interface publique)
      - data-network # Communique en interne avec Prometheus

# Volumes persistants
volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

# Déclaration et création des 3 réseaux distincts (Segmentation)
networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge
  data-network:
    driver: bridge