apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: calcul-hpa
  namespace: greenops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calcul-deployment # Cible votre microservice de calcul
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Seuil de déclenchement à 50% de CPU

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lecture-hpa
  namespace: greenops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lecture-deployment # Cible votre microservice de lecture
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Seuil de déclenchement à 50% de CPU

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alertes-hpa
  namespace: greenops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alertes-deployment # Cible votre microservice d'alertes
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Seuil de déclenchement à 50% de CPU

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
  namespace: greenops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-deployment # Cible votre microservice d'authentification
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Seuil de déclenchement à 50% de CPU

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: greenops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment # Cible votre microservice frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Seuil de déclenchement à 50% de CPU
