apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: greenops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "greenuser"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: greenops-secrets
              key: RABBITMQ_DEFAULT_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: greenops
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  selector:
    app: rabbitmq