apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: greenops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis # Correspond exactement à la valeur REDIS_HOST de votre ConfigMap
  namespace: greenops
spec:
  ports:
    - port: 6379
  selector:
    app: redis